"""Emit every generated theme file from fsim_theme/tokens.json.

Run: python -m fsim_theme.build [--out ROOT]

ROOT defaults to the repo root. Output is deterministic (LF line endings,
fixed key order), so running twice yields no diff. Generated files are
committed; never edit them by hand.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fsim_theme import MODES, THEME_DIR, load_tokens

REPO_ROOT = THEME_DIR.parent

# generated path (relative to ROOT) -> emitter
CSS_REL = "fsim_studio/web/css/tokens.css"
MPL_REL = {"light": "fsim_theme/fsim.mplstyle", "dark": "fsim_theme/fsim-dark.mplstyle"}
PLOTLY_REL = {m: f"fsim_theme/plotly_fsim_{m}.json" for m in MODES}

HEADER = "GENERATED by python -m fsim_theme.build from fsim_theme/tokens.json -- do not edit."


def _css_font_stack(primary: str, fallbacks: list[str]) -> str:
    def q(name: str) -> str:
        generic = {"sans-serif", "serif", "monospace", "system-ui", "ui-monospace"}
        return name if name in generic else f'"{name}"'
    return ", ".join(q(n) for n in [primary, *fallbacks])


def emit_css(tok: dict) -> str:
    f = tok["font"]
    lines = [f"/* {HEADER} */", ""]
    for face in f["faces"]:
        lines += [
            "@font-face {",
            f'  font-family: "{face["family"]}";',
            "  font-style: normal;",
            f"  font-weight: {face['weight']};",
            "  font-display: swap;",
            f'  src: url("../vendor/fonts/{face["woff2"]}") format("woff2");',
            "}",
        ]
    lines += ["", ":root {"]
    lines.append(f"  --font-ui: {_css_font_stack(f['ui'], f['fallback']['ui'])};")
    lines.append(f"  --font-label: {_css_font_stack(f['label'], f['fallback']['label'])};")
    lines.append(f"  --font-mono: {_css_font_stack(f['mono'], f['fallback']['mono'])};")
    lines.append(f"  --font-num: {_css_font_stack(f['num'], f['fallback']['num'])};")
    lines.append(f"  --label-tracking: {f['label_tracking']};")
    for k, v in tok["size"].items():
        lines.append(f"  --size-{k.replace('_', '-')}: {v}px;")
    for k, v in tok["mark"].items():
        unit = "" if ("opacity" in k or k.endswith("_mpl")) else "px"
        lines.append(f"  --mark-{k.replace('_', '-')}: {v}{unit};")
    for t, form in tok["tag"].items():
        tl = t.lower()
        lines.append(f"  --tag-{tl}-chip: {form['chip']};")
        lines.append(f"  --tag-{tl}-dash: {form['dash']};")
        lines.append(f"  --tag-{tl}-width: {form['width']}px;")
    lines.append(f"  --radius: {tok['radius']}px;")
    lines.append(f"  --space: {tok['space']}px;")
    lines.append("}")
    tag_names = list(tok["tag"])
    for mode in ("dark", "light"):
        c = tok["color"][mode]
        lines += ["", f"[data-theme={mode}] {{", f"  color-scheme: {mode};"]
        for k, v in c.items():
            if isinstance(v, list):
                if k == "ordinal_tag":
                    for t, hexv in zip(tag_names, v):
                        lines.append(f"  --ordinal-tag-{t.lower()}: {hexv};")
                else:
                    for i, hexv in enumerate(v, 1):
                        lines.append(f"  --{k}-{i}: {hexv};")
            elif isinstance(v, dict):
                for kk, hexv in v.items():
                    lines.append(f"  --{k}-{kk}: {hexv};")
            else:
                lines.append(f"  --{k}: {v};")
        lines.append("}")
    return "\n".join(lines) + "\n"


def _mpl_hex(h: str) -> str:
    # '#' starts a comment in matplotlibrc; matplotlib accepts bare hex.
    return h.lstrip("#")


def emit_mplstyle(tok: dict, mode: str) -> str:
    c = tok["color"][mode]
    f = tok["font"]
    m = tok["mark"]
    s = tok["size"]
    fam = ", ".join([f["ui"], *f["fallback"]["matplotlib"]])
    mono = ", ".join([f["mono"], "DejaVu Sans Mono"])
    cyc = ", ".join(f"'{_mpl_hex(h)}'" for h in c["series"])
    rows = [
        f"# {HEADER}",
        f"# mode: {mode}",
        "",
        f"font.family: {fam}",
        f"font.monospace: {mono}",
        f"font.size: {s['axis_title'] - 2}",
        "mathtext.fontset: dejavusans",
        f"text.color: {_mpl_hex(c['ink-1'])}",
        "",
        f"figure.facecolor: {_mpl_hex(c['surface'])}",
        f"figure.edgecolor: {_mpl_hex(c['surface'])}",
        f"savefig.facecolor: {_mpl_hex(c['surface'])}",
        f"savefig.edgecolor: {_mpl_hex(c['surface'])}",
        "savefig.dpi: 200",
        "",
        f"axes.facecolor: {_mpl_hex(c['surface'])}",
        f"axes.edgecolor: {_mpl_hex(c['axis'])}",
        f"axes.labelcolor: {_mpl_hex(c['ink-2'])}",
        f"axes.titlecolor: {_mpl_hex(c['ink-1'])}",
        "axes.titleweight: 600",
        f"axes.titlesize: {s['chart_title'] - 3}",
        f"axes.labelsize: {s['axis_title'] - 3}",
        "axes.spines.top: False",
        "axes.spines.right: False",
        "axes.grid: True",
        "axes.axisbelow: True",
        f"axes.prop_cycle: cycler('color', [{cyc}])",
        "",
        "grid.linestyle: -",
        f"grid.linewidth: {m['grid_mpl']}",
        f"grid.color: {_mpl_hex(c['grid'])}",
        "",
        f"lines.linewidth: {m['line_mpl']}",
        "lines.markersize: 5",
        "",
        "xtick.direction: out",
        "ytick.direction: out",
        f"xtick.color: {_mpl_hex(c['axis'])}",
        f"ytick.color: {_mpl_hex(c['axis'])}",
        f"xtick.labelcolor: {_mpl_hex(c['ink-2'])}",
        f"ytick.labelcolor: {_mpl_hex(c['ink-2'])}",
        "",
        "legend.frameon: False",
        f"legend.labelcolor: {_mpl_hex(c['ink-2'])}",
    ]
    return "\n".join(rows) + "\n"


def emit_plotly(tok: dict, mode: str) -> dict:
    c = tok["color"][mode]
    f = tok["font"]
    s = tok["size"]
    m = tok["mark"]
    ui = ", ".join([f["ui"], *f["fallback"]["ui"]])
    mono = ", ".join([f["num"], *f["fallback"]["num"]])  # ticks/hover: tabular Barlow
    n = len(c["seq"]) - 1
    seq_scale = [[round(i / n, 6), h] for i, h in enumerate(c["seq"])]
    axis = {
        "showgrid": True,
        "gridcolor": c["grid"],
        "gridwidth": m["grid"],
        "zeroline": False,
        "showline": True,
        "linecolor": c["axis"],
        "linewidth": 1,
        "ticks": "outside",
        "ticklen": m["tick_len"],
        "tickcolor": c["axis"],
        "tickfont": {"family": mono, "size": s["tick"], "color": c["ink-2"]},
        "title": {"font": {"family": ui, "size": s["axis_title"], "color": c["ink-2"]}},
        "automargin": True,
    }
    scene_axis = dict(axis, backgroundcolor=c["surface"], showbackground=True,
                      zerolinecolor=c["axis"])
    scene_axis.pop("automargin")
    colorbar = {"outlinewidth": 0, "ticks": "outside", "ticklen": m["tick_len"],
                "tickcolor": c["axis"],
                "tickfont": {"family": mono, "size": s["tick"], "color": c["ink-2"]}}
    return {
        "layout": {
            "paper_bgcolor": c["surface"],
            "plot_bgcolor": c["surface"],
            "font": {"family": ui, "size": s["chart_font"], "color": c["ink-2"]},
            "title": {"font": {"family": ui, "size": s["chart_title"], "weight": 600,
                               "color": c["ink-1"]},
                      "x": 0, "xanchor": "left"},
            "colorway": list(c["series"]),
            "xaxis": axis,
            "yaxis": axis,
            "scene": {"xaxis": scene_axis, "yaxis": scene_axis, "zaxis": scene_axis,
                      "bgcolor": c["surface"]},
            "hovermode": "x unified",
            "hoverlabel": {"bgcolor": c["plate"], "bordercolor": c["rim"],
                           "font": {"family": mono, "size": s["tick"], "color": c["ink-1"]}},
            "legend": {"orientation": "h", "x": 0, "xanchor": "left", "y": 1.02,
                       "yanchor": "bottom", "borderwidth": 0, "bgcolor": "rgba(0,0,0,0)",
                       "font": {"family": ui, "size": s["tick"], "color": c["ink-2"]}},
            "margin": {"l": 56, "r": 16, "t": 40, "b": 48},
            "modebar": {"bgcolor": "rgba(0,0,0,0)", "color": c["muted"],
                        "activecolor": c["ink-1"]},
            "colorscale": {"sequential": seq_scale,
                           "diverging": [[0, c["div"][0]], [0.5, c["div"][1]],
                                         [1, c["div"][2]]]},
            "coloraxis": {"colorbar": colorbar},
        },
        "data": {
            "scatter": [{"line": {"width": m["line"]},
                         "marker": {"size": 2 * m["marker_radius"],
                                    "line": {"width": m["marker_ring"],
                                             "color": c["surface"]}}}],
            "bar": [{"marker": {"line": {"width": 0}}}],
            "heatmap": [{"colorscale": seq_scale, "colorbar": colorbar}],
            "contour": [{"colorscale": seq_scale, "colorbar": colorbar}],
            "surface": [{"colorscale": seq_scale, "colorbar": colorbar,
                         "lighting": {"ambient": 0.6, "diffuse": 0.6, "specular": 0.15}}],
        },
    }


def generate(tok: dict | None = None) -> dict[str, str]:
    """Return {relative path: file text} for every generated file."""
    tok = load_tokens() if tok is None else tok
    out = {CSS_REL: emit_css(tok)}
    for mode in MODES:
        out[MPL_REL[mode]] = emit_mplstyle(tok, mode)
        out[PLOTLY_REL[mode]] = json.dumps(emit_plotly(tok, mode), indent=2) + "\n"
    return out


def build(root: Path | str | None = None) -> list[Path]:
    """Write every generated file under `root` (default: repo root)."""
    root = REPO_ROOT if root is None else Path(root)
    written = []
    for rel, text in generate().items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        written.append(p)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=None, help="root directory (default: repo root)")
    args = ap.parse_args(argv)
    for p in build(args.out):
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
